[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Choose a default "cargo run" tool
# - `probe-rs` provides flashing and defmt via a hardware debugger, and stack unwind on panic
# - elf2uf2-rs loads firmware over USB when the rp2040 is in boot mode
runner = "probe-rs run --chip RP2040"
# runner = "elf2uf2-rs -d"

[build]
# This is the cross compilation target we will use
# Read about what processors this targets: https://doc.rust-lang.org/nightly/rustc/platform-support/thumbv6m-none-eabi.html
# Read about targets in general: https://doc.rust-lang.org/nightly/rustc/platform-support.html
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"
